import React from 'react';
import { Product, User } from '../types';

interface InvoiceViewProps { 
  product: Product; 
  user: User; 
  date: string; 
}

export const InvoiceView: React.FC<InvoiceViewProps> = ({ product, user, date }) => (
    <div className="bg-white p-8 border border-slate-200 rounded-lg shadow-sm max-w-2xl mx-auto my-8 font-mono text-sm text-slate-900">
        <div className="flex justify-between items-center border-b border-slate-200 pb-4 mb-6">
            <div className="text-2xl font-bold text-slate-900">INVOICE</div>
            <div className="text-right">
                <div className="font-bold text-lg text-indigo-600">AutoResolve Inc.</div>
                <div className="text-slate-500">Order #{product.orderId || `ORD-${Date.now()}`}</div>
            </div>
        </div>
        <div className="grid grid-cols-2 gap-8 mb-8">
            <div>
                <div className="text-xs text-slate-400 uppercase tracking-wider mb-1">Bill To</div>
                <div className="font-bold text-slate-900">{user.name}</div>
                <div className="text-slate-600">{user.email}</div>
                <div className="text-slate-600">Customer ID: {user.id}</div>
            </div>
            <div className="text-right">
                 <div className="text-xs text-slate-400 uppercase tracking-wider mb-1">Date</div>
                 <div className="font-bold text-slate-900">{date}</div>
                 <div className="mt-2 text-xs text-slate-400 uppercase tracking-wider mb-1">Status</div>
                 <div className="text-emerald-600 font-bold">PAID</div>
            </div>
        </div>
        <table className="w-full mb-8">
            <thead>
                <tr className="border-b-2 border-slate-100 text-left text-xs uppercase text-slate-500">
                    <th className="py-2">Item Description</th>
                    <th className="py-2 text-right">Qty</th>
                    <th className="py-2 text-right">Price</th>
                </tr>
            </thead>
            <tbody>
                <tr className="border-b border-slate-50">
                    <td className="py-4 font-medium text-slate-900">{product.name}</td>
                    <td className="py-4 text-right text-slate-600">1</td>
                    <td className="py-4 text-right text-slate-900">${product.price.toFixed(2)}</td>
                </tr>
            </tbody>
            <tfoot>
                 <tr>
                    <td className="pt-4"></td>
                    <td className="pt-4 text-right font-bold text-slate-900">Total</td>
                    <td className="pt-4 text-right font-bold text-indigo-600 text-lg">${product.price.toFixed(2)}</td>
                </tr>
            </tfoot>
        </table>
        <div className="flex justify-center mt-12">
            <div className="bg-slate-50 px-6 py-3 rounded-full text-center text-slate-400 text-xs border border-slate-100">
                Generated by AutoResolve Python Backend • SQL Transaction ID: {Date.now()}
            </div>
        </div>
    </div>
);
